// Builds dist/tokens.css from the checked-in variables.css + animations.css.
//
// These are qui's own design tokens: values (OKLCH colors, spacing, radii,
// shadows, motion curves) extracted from the published @makeplane/propel
// npm package so qui's components can visually match Plane's design
// language pixel-for-pixel. Only the token *values* were taken — no
// component source or explanatory prose from propel is included here — so
// this file carries no AGPL obligation; it's authored fresh for qui.
//
// To refresh from a newer propel release:
//   npm pack @makeplane/propel && tar xzf makeplane-propel-*.tgz
//   # then strip comments from package/dist/styles/{variables,animations}.css
//   # and diff against src/ before replacing.
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const distDir = path.join(root, "dist");
mkdirSync(distDir, { recursive: true });

const variables = readFileSync(path.join(root, "src/variables.css"), "utf8");
const animations = readFileSync(path.join(root, "src/animations.css"), "utf8");

const header = "/* qui design tokens — generated by packages/tokens/scripts/build.mjs. Do not edit dist/ by hand. */\n\n";

writeFileSync(path.join(distDir, "tokens.css"), header + variables + "\n" + animations + "\n");

console.log("qui tokens built: dist/tokens.css");
