// AUTO-GENERATED by apps/playground/scripts/generate-components-page.mjs — do not
// hand-edit this file. Add or change a component's demo by editing the __DOC ... DOC__
// (or __DOC_BLOCK ... DOC__ for a full-width demo) comment in its source file, then run:
//   pnpm --filter playground run docs:gen
import * as React from "react";
import * as QUI from "@qui/ui";
import * as Icons from "lucide-react";

function Section({
  title,
  children,
  align = "row",
}: {
  title: string;
  children: React.ReactNode;
  align?: "row" | "block";
}) {
  return (
    <section className="flex flex-col gap-3">
      <h2 className="text-sm font-semibold uppercase tracking-wide text-tertiary">{title}</h2>
      <div
        className={
          align === "row"
            ? "flex flex-wrap items-center gap-4 rounded-lg border border-subtle bg-layer-1 p-4"
            : "overflow-hidden rounded-lg border border-subtle bg-layer-1"
        }
      >
        {children}
      </div>
    </section>
  );
}

export function ComponentsPage() {
  return (
    <div className="flex flex-col gap-8">
      <div>
        <h1 className="text-2xl font-semibold text-primary">Components</h1>
        <p className="text-sm text-secondary">Every component and variant, grouped by atomic level.</p>
      </div>

      <div>
        <h1 className="mb-3 text-base font-semibold">Atoms</h1>
        <div className="flex flex-col gap-6">
          <Section title="Button" align="block">
<div className="flex flex-col gap-4 p-4">
  <div className="flex flex-wrap items-center gap-3">
    <QUI.Button variant="primary" label="Primary" />
    <QUI.Button variant="secondary" label="Secondary" />
    <QUI.Button variant="tertiary" label="Tertiary" />
    <QUI.Button variant="ghost" label="Ghost" />
    <QUI.Button variant="danger" label="Danger" />
    <QUI.Button variant="danger-outline" label="Danger outline" />
  </div>
  <div className="flex flex-wrap items-center gap-3">
    <QUI.Button size="xs" label="xs" />
    <QUI.Button size="sm" label="sm" />
    <QUI.Button size="md" label="md" />
    <QUI.Button size="lg" label="lg" />
  </div>
  <div className="flex flex-wrap items-center gap-3">
    <QUI.Button label="Loading" loading />
    <QUI.Button label="Disabled" disabled />
    <QUI.Button variant="secondary" label="Loading" loading />
  </div>
</div>
          </Section>
          <Section title="Icon" align="row">
<div className="flex items-center gap-3 [--node-size:20px]">
  <QUI.Icon icon={Icons.Settings} tint="secondary" />
  <QUI.Icon icon={Icons.Settings} tint="muted" />
  <QUI.Icon icon={Icons.Settings} tint="danger" />
  <QUI.Icon icon={Icons.Settings} tint="placeholder" />
</div>
          </Section>
          <Section title="IconButton" align="block">
<div className="flex flex-col gap-4 p-4">
  <div className="flex flex-wrap items-center gap-3">
    <QUI.IconButton variant="primary" aria-label="Add" icon={<QUI.Icon icon={Icons.Plus} />} />
    <QUI.IconButton variant="secondary" aria-label="Settings" icon={<QUI.Icon icon={Icons.Settings} />} />
    <QUI.IconButton variant="tertiary" aria-label="More" icon={<QUI.Icon icon={Icons.MoreHorizontal} />} />
    <QUI.IconButton variant="ghost" aria-label="Close" icon={<QUI.Icon icon={Icons.X} />} />
    <QUI.IconButton variant="danger" aria-label="Delete" icon={<QUI.Icon icon={Icons.Trash2} />} />
    <QUI.IconButton variant="danger-outline" aria-label="Delete" icon={<QUI.Icon icon={Icons.Trash2} />} />
  </div>
  <div className="flex flex-wrap items-center gap-3">
    <QUI.IconButton size="xs" aria-label="Add" icon={<QUI.Icon icon={Icons.Plus} />} />
    <QUI.IconButton size="sm" aria-label="Add" icon={<QUI.Icon icon={Icons.Plus} />} />
    <QUI.IconButton size="md" aria-label="Add" icon={<QUI.Icon icon={Icons.Plus} />} />
    <QUI.IconButton size="lg" aria-label="Add" icon={<QUI.Icon icon={Icons.Plus} />} />
  </div>
  <div className="flex flex-wrap items-center gap-3">
    <QUI.IconButton aria-label="Loading" icon={<QUI.Icon icon={Icons.Plus} />} loading />
    <QUI.IconButton aria-label="Disabled" icon={<QUI.Icon icon={Icons.Plus} />} disabled />
  </div>
</div>
          </Section>
          <Section title="Spinner" align="row">
<div className="[--node-size:20px] text-icon-secondary">
  <QUI.Spinner />
</div>
          </Section>
          <Section title="Tooltip" align="row">
<QUI.Tooltip label="Save changes">
  <QUI.Button label="Hover me" />
</QUI.Tooltip>
          </Section>
        </div>
      </div>
    </div>
  );
}
