// AUTO-GENERATED by apps/playground/scripts/generate-components-page.mjs — do not
// hand-edit this file. Add or change a component's demo by editing the __DOC ... DOC__
// (or __DOC_BLOCK ... DOC__ for a full-width demo) comment in its source file, and its
// prop options by editing the __PROPS {...} PROPS__ comment, then run:
//   pnpm --filter playground run docs:gen
import * as React from "react";
import * as QUI from "@qui/ui";
import * as Icons from "lucide-react";

type PropsSpec = Record<string, ReadonlyArray<string | number> | "boolean">;

function PropsPanel({ props }: { props: PropsSpec }) {
  return (
    <dl className="flex w-56 shrink-0 flex-col gap-3 border-s border-subtle p-4">
      {Object.entries(props).map(([name, values]) => (
        <div key={name} className="flex flex-col gap-1">
          <dt className="font-mono text-caption-md-medium text-primary">{name}</dt>
          <dd className="flex flex-wrap gap-1">
            {values === "boolean"
              ? ["true", "false"].map((v) => (
                  <span key={v} className="rounded-sm bg-layer-3 px-1.5 py-0.5 font-mono text-caption-md-regular text-tertiary">
                    {v}
                  </span>
                ))
              : values.map((v) => (
                  <span key={v} className="rounded-sm bg-layer-3 px-1.5 py-0.5 font-mono text-caption-md-regular text-tertiary">
                    {v}
                  </span>
                ))}
          </dd>
        </div>
      ))}
    </dl>
  );
}

function Section({
  title,
  children,
  align = "row",
  props,
}: {
  title: string;
  children: React.ReactNode;
  align?: "row" | "block";
  props?: PropsSpec;
}) {
  return (
    <section className="flex flex-col gap-3">
      <h2 className="text-sm font-semibold uppercase tracking-wide text-tertiary">{title}</h2>
      <div className="flex overflow-hidden rounded-lg border border-subtle bg-layer-1">
        <div className={align === "row" ? "flex flex-1 flex-wrap items-center gap-4 p-4" : "flex-1 overflow-hidden"}>{children}</div>
        {props ? <PropsPanel props={props} /> : null}
      </div>
    </section>
  );
}

export function ComponentsPage() {
  return (
    <div className="flex flex-col gap-8">
      <div>
        <h1 className="text-2xl font-semibold text-primary">Components</h1>
        <p className="text-sm text-secondary">Every component and variant, grouped by atomic level.</p>
      </div>

      <div>
        <h1 className="mb-3 text-base font-semibold">Atoms</h1>
        <div className="flex flex-col gap-6">
          <Section title="Avatar" align="block" props={{"size":["2xs","xs","sm","md","lg","xl","2xl","3xl"],"tooltip":"boolean"}}>
<div className="flex flex-wrap items-center gap-4 p-4">
  <QUI.Avatar size="2xs" alt="Ada Lovelace" />
  <QUI.Avatar size="xs" alt="Ada Lovelace" />
  <QUI.Avatar size="sm" alt="Ada Lovelace" />
  <QUI.Avatar size="md" alt="Ada Lovelace" />
  <QUI.Avatar size="lg" alt="Ada Lovelace" />
  <QUI.Avatar size="xl" alt="Ada Lovelace" />
  <QUI.Avatar size="2xl" alt="Ada Lovelace" />
  <QUI.Avatar size="md" alt="Grace Hopper" />
  <QUI.Avatar size="md" alt="Barbara Liskov" />
  <QUI.Avatar size="md" />
  <QUI.Avatar size="md" alt="Katherine Johnson" tooltip />
</div>
          </Section>
          <Section title="AvatarGroup" align="row" props={{"size":["2xs","xs","sm","md","lg","xl","2xl","3xl"],"max":["number"]}}>
<QUI.AvatarGroup size="md" max={3} overflowTooltip="Dana, Erin">
  <QUI.Avatar alt="Ada Lovelace" />
  <QUI.Avatar alt="Grace Hopper" />
  <QUI.Avatar alt="Barbara Liskov" />
  <QUI.Avatar alt="Dana Scott" />
  <QUI.Avatar alt="Erin Meyer" />
</QUI.AvatarGroup>
          </Section>
          <Section title="Badge" align="block" props={{"variant":["neutral","grey","brand","info","purple","indigo","success","emerald","warning","yellow","danger","crimson","orange"],"size":["xs","sm","md"]}}>
<div className="flex flex-col gap-4 p-4">
  <div className="flex flex-wrap items-center gap-2">
    <QUI.Badge label="Neutral" />
    <QUI.Badge variant="grey" label="Grey" />
    <QUI.Badge variant="brand" label="Brand" />
    <QUI.Badge variant="info" label="Info" />
    <QUI.Badge variant="purple" label="Purple" />
    <QUI.Badge variant="indigo" label="Indigo" />
    <QUI.Badge variant="success" label="Success" />
    <QUI.Badge variant="emerald" label="Emerald" />
    <QUI.Badge variant="warning" label="Warning" />
    <QUI.Badge variant="yellow" label="Yellow" />
    <QUI.Badge variant="danger" label="Danger" />
    <QUI.Badge variant="crimson" label="Crimson" />
    <QUI.Badge variant="orange" label="Orange" />
  </div>
  <div className="flex flex-wrap items-center gap-2">
    <QUI.Badge size="xs" variant="brand" label="xs" />
    <QUI.Badge size="sm" variant="brand" label="sm" />
    <QUI.Badge size="md" variant="brand" label="md" />
    <QUI.Badge variant="success" label="With icon" startIcon={<QUI.Icon icon={Icons.Check} />} />
  </div>
</div>
          </Section>
          <Section title="Button" align="block" props={{"variant":["primary","secondary","tertiary","ghost","danger","danger-outline"],"size":["xs","sm","md","lg"],"stretch":["auto","full"],"iconPosition":["start","end"],"loading":"boolean","disabled":"boolean"}}>
<div className="flex flex-col gap-4 p-4">
  <div className="flex flex-wrap items-center gap-3">
    <QUI.Button variant="primary" label="Primary" />
    <QUI.Button variant="secondary" label="Secondary" />
    <QUI.Button variant="tertiary" label="Tertiary" />
    <QUI.Button variant="ghost" label="Ghost" />
    <QUI.Button variant="danger" label="Danger" />
    <QUI.Button variant="danger-outline" label="Danger outline" />
  </div>
  <div className="flex flex-wrap items-center gap-3">
    <QUI.Button size="xs" label="xs" />
    <QUI.Button size="sm" label="sm" />
    <QUI.Button size="md" label="md" />
    <QUI.Button size="lg" label="lg" />
  </div>
  <div className="flex flex-wrap items-center gap-3">
    <QUI.Button label="Loading" loading />
    <QUI.Button label="Disabled" disabled />
    <QUI.Button variant="secondary" label="Loading" loading />
  </div>
</div>
          </Section>
          <Section title="Checkbox" align="block" props={{"stretch":["auto","full"],"indeterminate":"boolean","disabled":"boolean","defaultChecked":"boolean"}}>
<div className="flex flex-col gap-1 p-4">
  <QUI.Checkbox label="Unchecked" />
  <QUI.Checkbox label="Checked" defaultChecked />
  <QUI.Checkbox label="Indeterminate" indeterminate />
  <QUI.Checkbox label="Disabled" disabled />
  <QUI.Checkbox label="Disabled checked" disabled defaultChecked />
</div>
          </Section>
          <Section title="CircularProgress" align="row" props={{"size":["sm","md"],"variant":["brand","success","warning","danger"],"indeterminate":"boolean"}}>
<div className="flex items-center gap-4 p-4">
  <QUI.CircularProgress size="sm" value={40} />
  <QUI.CircularProgress size="md" value={70} />
  <QUI.CircularProgress size="md" value={70} variant="success" />
  <QUI.CircularProgress size="md" value={70} variant="warning" />
  <QUI.CircularProgress size="md" value={70} variant="danger" />
  <QUI.CircularProgress size="md" indeterminate />
</div>
          </Section>
          <Section title="Icon" align="row" props={{"tint":["inherit","danger","placeholder","muted","secondary","tertiary"],"size":["inherit","xs","sm","md","lg","xl","2xl"]}}>
<div className="flex items-center gap-3 [--node-size:20px]">
  <QUI.Icon icon={Icons.Settings} tint="secondary" />
  <QUI.Icon icon={Icons.Settings} tint="muted" />
  <QUI.Icon icon={Icons.Settings} tint="danger" />
  <QUI.Icon icon={Icons.Settings} tint="placeholder" />
</div>
          </Section>
          <Section title="IconButton" align="block" props={{"variant":["primary","secondary","tertiary","ghost","danger","danger-outline"],"size":["xs","sm","md","lg"],"showTooltip":"boolean","loading":"boolean","disabled":"boolean"}}>
<div className="flex flex-col gap-4 p-4">
  <div className="flex flex-wrap items-center gap-3">
    <QUI.IconButton variant="primary" aria-label="Add" icon={<QUI.Icon icon={Icons.Plus} />} />
    <QUI.IconButton variant="secondary" aria-label="Settings" icon={<QUI.Icon icon={Icons.Settings} />} />
    <QUI.IconButton variant="tertiary" aria-label="More" icon={<QUI.Icon icon={Icons.MoreHorizontal} />} />
    <QUI.IconButton variant="ghost" aria-label="Close" icon={<QUI.Icon icon={Icons.X} />} />
    <QUI.IconButton variant="danger" aria-label="Delete" icon={<QUI.Icon icon={Icons.Trash2} />} />
    <QUI.IconButton variant="danger-outline" aria-label="Delete" icon={<QUI.Icon icon={Icons.Trash2} />} />
  </div>
  <div className="flex flex-wrap items-center gap-3">
    <QUI.IconButton size="xs" aria-label="Add" icon={<QUI.Icon icon={Icons.Plus} />} />
    <QUI.IconButton size="sm" aria-label="Add" icon={<QUI.Icon icon={Icons.Plus} />} />
    <QUI.IconButton size="md" aria-label="Add" icon={<QUI.Icon icon={Icons.Plus} />} />
    <QUI.IconButton size="lg" aria-label="Add" icon={<QUI.Icon icon={Icons.Plus} />} />
  </div>
  <div className="flex flex-wrap items-center gap-3">
    <QUI.IconButton aria-label="Loading" icon={<QUI.Icon icon={Icons.Plus} />} loading />
    <QUI.IconButton aria-label="Disabled" icon={<QUI.Icon icon={Icons.Plus} />} disabled />
  </div>
</div>
          </Section>
          <Section title="Input" align="block" props={{"size":["md","lg","xl","2xl"],"disabled":"boolean"}}>
<div className="flex flex-col gap-3 p-4">
  <QUI.Input placeholder="Search…" size="md" startSlot={<QUI.Icon icon={Icons.Search} tint="placeholder" />} />
  <QUI.Input placeholder="Large" size="lg" />
  <QUI.Input placeholder="Extra large" size="xl" />
  <QUI.Input placeholder="2xl" size="2xl" />
  <QUI.Input placeholder="Disabled" disabled />
</div>
          </Section>
          <Section title="LinearProgress" align="block" props={{"size":["sm","md"],"variant":["brand","success","warning","danger"],"indeterminate":"boolean","showValue":"boolean"}}>
<div className="flex flex-col gap-4 p-4">
  <QUI.LinearProgress label="Uploading" value={62} />
  <QUI.LinearProgress size="sm" variant="success" value={100} />
  <QUI.LinearProgress variant="warning" value={40} />
  <QUI.LinearProgress variant="danger" value={15} />
  <QUI.LinearProgress indeterminate />
</div>
          </Section>
          <Section title="NumberField" align="row" props={{"size":["sm","md","lg"],"disabled":"boolean"}}>
<div className="flex items-center gap-4 p-4">
  <QUI.NumberField size="sm" aria-label="Quantity" defaultValue={1} min={0} max={10} />
  <QUI.NumberField size="md" aria-label="Quantity" defaultValue={1} min={0} max={10} />
  <QUI.NumberField size="lg" aria-label="Quantity" defaultValue={1} min={0} max={10} />
  <QUI.NumberField size="md" aria-label="Quantity" defaultValue={1} disabled />
</div>
          </Section>
          <Section title="Pill" align="block" props={{"variant":["outline","soft","ghost"],"size":["xs","sm","md"],"loading":"boolean","placeholder":"boolean","disabled":"boolean"}}>
<div className="flex flex-col gap-4 p-4">
  <div className="flex flex-wrap items-center gap-3">
    <QUI.Pill variant="outline" label="Outline" startIcon={<QUI.Icon icon={Icons.Filter} />} />
    <QUI.Pill variant="soft" label="Soft" startIcon={<QUI.Icon icon={Icons.Filter} />} />
    <QUI.Pill variant="ghost" label="Ghost" startIcon={<QUI.Icon icon={Icons.Filter} />} />
  </div>
  <div className="flex flex-wrap items-center gap-3">
    <QUI.Pill size="xs" label="xs" />
    <QUI.Pill size="sm" label="sm" />
    <QUI.Pill size="md" label="md" />
  </div>
  <div className="flex flex-wrap items-center gap-3">
    <QUI.Pill label="Placeholder" placeholder />
    <QUI.Pill label="Loading" loading />
    <QUI.Pill label="Disabled" disabled />
  </div>
</div>
          </Section>
          <Section title="Radio" align="row" props={{"disabled":"boolean"}}>
<QUI.RadioGroup defaultValue="a" className="flex-row gap-4">
  <QUI.Radio value="a" aria-label="Option A" />
  <QUI.Radio value="b" aria-label="Option B" />
  <QUI.Radio value="c" aria-label="Option C (disabled)" disabled />
</QUI.RadioGroup>
          </Section>
          <Section title="RadioGroup" align="block" props={{"density":["comfortable","compact"]}}>
<QUI.RadioGroup defaultValue="md" className="p-4">
  <QUI.RadioOption value="sm" label="Small" />
  <QUI.RadioOption value="md" label="Medium" />
  <QUI.RadioOption value="lg" label="Large" />
  <QUI.RadioOption value="xl" label="Extra large (disabled)" disabled />
</QUI.RadioGroup>
          </Section>
          <Section title="Separator" align="row" props={{"orientation":["horizontal","vertical"],"decorative":"boolean"}}>
<div className="flex w-full flex-col gap-3">
  <span className="text-sm text-secondary">Above</span>
  <QUI.Separator />
  <span className="text-sm text-secondary">Below</span>
  <div className="flex h-6 items-center gap-3">
    <span className="text-sm text-secondary">Left</span>
    <QUI.Separator orientation="vertical" />
    <span className="text-sm text-secondary">Right</span>
  </div>
</div>
          </Section>
          <Section title="Skeleton" align="block" props={{"layout":["stack","row"],"stretch":["full","fit"]}}>
<div className="flex flex-col gap-6 p-4">
  <QUI.Skeleton aria-label="Loading card" inlineSize="16rem">
    <QUI.SkeletonItem blockSize="1.25rem" />
    <QUI.SkeletonItem blockSize="0.875rem" inlineSize="10rem" />
  </QUI.Skeleton>
  <QUI.Skeleton aria-label="Loading profile" layout="row">
    <QUI.SkeletonItem variant="circle" inlineSize="2.5rem" blockSize="2.5rem" />
    <QUI.Skeleton aria-label="" inlineSize="12rem">
      <QUI.SkeletonItem blockSize="1rem" />
      <QUI.SkeletonItem blockSize="0.875rem" inlineSize="8rem" />
    </QUI.Skeleton>
  </QUI.Skeleton>
</div>
          </Section>
          <Section title="Spinner" align="row" props={{"active":"boolean"}}>
<div className="[--node-size:20px] text-icon-secondary">
  <QUI.Spinner />
</div>
          </Section>
          <Section title="Switch" align="block" props={{"size":["sm","md","lg"],"disabled":"boolean","readOnly":"boolean","defaultChecked":"boolean"}}>
<div className="flex flex-col gap-4 p-4">
  <div className="flex items-center gap-3">
    <QUI.Switch size="sm" />
    <QUI.Switch size="md" />
    <QUI.Switch size="lg" />
  </div>
  <div className="flex items-center gap-3">
    <QUI.Switch defaultChecked />
    <QUI.Switch disabled />
    <QUI.Switch disabled defaultChecked />
  </div>
</div>
          </Section>
          <Section title="TextArea" align="block" props={{"size":["md","lg","xl","2xl"],"resize":["none","vertical","both"],"autoResize":"boolean","disabled":"boolean"}}>
<div className="flex flex-col gap-3 p-4">
  <QUI.TextArea placeholder="Write something…" size="md" />
  <QUI.TextArea placeholder="Auto-resizing, up to 6 rows" autoResize maxRows={6} />
  <QUI.TextArea placeholder="Disabled" disabled />
</div>
          </Section>
          <Section title="Tooltip" align="row" props={{"side":["top","bottom","left","right"],"sideOffset":["number"],"disabled":"boolean"}}>
<QUI.Tooltip label="Save changes">
  <QUI.Button label="Hover me" />
</QUI.Tooltip>
          </Section>
        </div>
      </div>

      <div>
        <h1 className="mb-3 text-base font-semibold">Molecules</h1>
        <div className="flex flex-col gap-6">
          <Section title="Accordion" align="block" props={{"multiple":"boolean","disabled":"boolean"}}>
<div className="flex w-full flex-col p-4">
  <QUI.Accordion defaultValue={["general"]}>
    <QUI.AccordionItem value="general">
      <QUI.AccordionTrigger label="General" icon={<QUI.Icon icon={Icons.Settings} />} />
      <QUI.AccordionPanel>Workspace name, URL, and timezone.</QUI.AccordionPanel>
    </QUI.AccordionItem>
    <QUI.AccordionItem value="members">
      <QUI.AccordionTrigger label="Members" />
      <QUI.AccordionPanel>Invite, roles, and permissions.</QUI.AccordionPanel>
    </QUI.AccordionItem>
    <QUI.AccordionItem value="billing" disabled>
      <QUI.AccordionTrigger label="Billing" />
      <QUI.AccordionPanel>Plan and invoices.</QUI.AccordionPanel>
    </QUI.AccordionItem>
  </QUI.Accordion>
</div>
          </Section>
          <Section title="AlertDialog" align="block" props={{"variant":["danger","warning","info","success"],"layout":["inline","split"]}}>
<div className="flex flex-col gap-4 p-4">
  <QUI.AlertDialog>
    <QUI.AlertDialogTrigger render={<QUI.Button variant="danger" label="Delete project" />} />
    <QUI.AlertDialogContent>
      <div className="flex flex-col gap-4 p-5 pb-3 max-sm:text-center">
        <QUI.AlertDialogIcon variant="danger">
          <QUI.Icon icon={Icons.Trash2} />
        </QUI.AlertDialogIcon>
        <div className="flex flex-col gap-1.5">
          <QUI.AlertDialogTitle>Delete this project?</QUI.AlertDialogTitle>
          <QUI.AlertDialogDescription>This can't be undone. All issues, cycles, and pages in this project will be permanently deleted.</QUI.AlertDialogDescription>
        </div>
      </div>
      <QUI.AlertDialogActions>
        <QUI.AlertDialogClose render={<QUI.Button variant="secondary" label="Cancel" />} />
        <QUI.Button variant="danger" label="Delete" />
      </QUI.AlertDialogActions>
    </QUI.AlertDialogContent>
  </QUI.AlertDialog>
</div>
          </Section>
          <Section title="Autocomplete" align="block" props={{"size":["md","lg","xl","2xl"],"disabled":"boolean","autoHighlight":["true","always"],"openOnInputClick":"boolean"}}>
<div className="flex flex-col gap-4 p-4">
  <QUI.Autocomplete items={["Afghanistan", "Albania", "Algeria", "Andorra", "Angola"]}>
    <QUI.AutocompleteInputGroup placeholder="Search countries…" className="w-64" />
    <QUI.AutocompleteContent>
      {(item) => <QUI.AutocompleteItem key={item} value={item}>{item}</QUI.AutocompleteItem>}
    </QUI.AutocompleteContent>
  </QUI.Autocomplete>
</div>
          </Section>
          <Section title="Breadcrumb" align="block" props={{"current":"boolean"}}>
<div className="flex flex-col gap-4 p-4">
  <QUI.Breadcrumb>
    <QUI.BreadcrumbItem href="#">Workspace</QUI.BreadcrumbItem>
    <QUI.BreadcrumbSeparator />
    <QUI.BreadcrumbItem href="#">Projects</QUI.BreadcrumbItem>
    <QUI.BreadcrumbSeparator />
    <QUI.BreadcrumbItem current>Settings</QUI.BreadcrumbItem>
  </QUI.Breadcrumb>
  <QUI.Breadcrumb>
    <QUI.BreadcrumbItem href="#" icon={<QUI.Icon icon={Icons.Home} />}>
      Home
    </QUI.BreadcrumbItem>
    <QUI.BreadcrumbSeparator />
    <QUI.BreadcrumbItem current icon={<QUI.Icon icon={Icons.Folder} />}>
      Documents
    </QUI.BreadcrumbItem>
  </QUI.Breadcrumb>
</div>
          </Section>
          <Section title="Combobox" align="block" props={{"size":["md","lg","xl","2xl"],"clearable":"boolean","disabled":"boolean","multiple":"boolean","autoHighlight":"boolean"}}>
<div className="flex flex-col gap-4 p-4">
  <QUI.Combobox items={["Apple", "Banana", "Cherry", "Date", "Elderberry"]} defaultValue="Banana">
    <QUI.ComboboxInputGroup placeholder="Search fruit…" className="w-64" />
    <QUI.ComboboxContent>
      {(item) => <QUI.ComboboxItem key={item} value={item}>{item}</QUI.ComboboxItem>}
    </QUI.ComboboxContent>
  </QUI.Combobox>
  <QUI.Combobox items={["Apple", "Banana", "Cherry"]} multiple defaultValue={["Apple"]}>
    <QUI.ComboboxInputGroup placeholder="Search fruit…" className="w-64" />
    <QUI.ComboboxContent>
      {(item) => <QUI.ComboboxItem key={item} value={item}>{item}</QUI.ComboboxItem>}
    </QUI.ComboboxContent>
  </QUI.Combobox>
</div>
          </Section>
          <Section title="ContextMenu" align="block" props={{"ContextMenuItem.variant":["neutral","accent","danger"],"ContextMenuItem.selected":"boolean"}}>
<QUI.ContextMenu>
  <QUI.ContextMenuTrigger className="flex h-32 w-full items-center justify-center rounded-lg border border-dashed border-subtle text-body-xs-regular text-tertiary">
    Right-click this area
  </QUI.ContextMenuTrigger>
  <QUI.ContextMenuContent>
    <QUI.ContextMenuItem icon={<QUI.Icon icon={Icons.Pencil} />}>Rename</QUI.ContextMenuItem>
    <QUI.ContextMenuItem icon={<QUI.Icon icon={Icons.Copy} />} trailing={<span className="text-caption-md-regular text-tertiary">⌘D</span>}>
      Duplicate
    </QUI.ContextMenuItem>
    <QUI.ContextMenuSeparator />
    <QUI.ContextMenuGroup>
      <QUI.ContextMenuGroupLabel>Danger zone</QUI.ContextMenuGroupLabel>
      <QUI.ContextMenuItem variant="danger" icon={<QUI.Icon icon={Icons.Trash} />}>
        Delete
      </QUI.ContextMenuItem>
    </QUI.ContextMenuGroup>
  </QUI.ContextMenuContent>
</QUI.ContextMenu>
          </Section>
          <Section title="Dialog" align="block" props={{"size":["xs","sm","md","lg","xl","full"],"hideClose":"boolean"}}>
<div className="flex flex-col gap-4 p-4">
  <QUI.Dialog>
    <QUI.DialogTrigger render={<QUI.Button label="Open dialog" />} />
    <QUI.DialogContent>
      <div className="flex flex-col gap-4 p-4 pe-10">
        <div className="flex flex-col gap-1.5">
          <QUI.DialogTitle>Invite teammates</QUI.DialogTitle>
          <QUI.DialogDescription>Send an invite link to anyone you want to collaborate with.</QUI.DialogDescription>
        </div>
        <QUI.Input placeholder="name@company.com" />
      </div>
      <div className="flex shrink-0 items-center justify-end gap-3 border-t border-subtle p-4">
        <QUI.DialogClose render={<QUI.Button variant="secondary" label="Cancel" />} />
        <QUI.Button label="Send invite" />
      </div>
    </QUI.DialogContent>
  </QUI.Dialog>
</div>
          </Section>
          <Section title="Drawer" align="block" props={{"side":["start","end"],"size":["sm","md","lg"],"hideClose":"boolean"}}>
<div className="flex flex-col gap-4 p-4">
  <QUI.Drawer>
    <QUI.DrawerTrigger render={<QUI.Button label="Open drawer" />} />
    <QUI.DrawerContent>
      <div className="flex min-h-0 flex-1 flex-col gap-4 overflow-y-auto p-4 pe-10">
        <div className="flex flex-col gap-1.5">
          <QUI.DrawerTitle>Filters</QUI.DrawerTitle>
          <QUI.DrawerDescription>Narrow down the issue list by state, priority, and assignee.</QUI.DrawerDescription>
        </div>
        <QUI.Input placeholder="Search filters" />
      </div>
      <div className="flex shrink-0 items-center justify-end gap-3 border-t border-subtle p-4">
        <QUI.DrawerClose render={<QUI.Button variant="secondary" label="Cancel" />} />
        <QUI.Button label="Apply" />
      </div>
    </QUI.DrawerContent>
  </QUI.Drawer>
</div>
          </Section>
          <Section title="Field" align="block" props={{"size":["md","lg","xl","2xl"],"required":"boolean"}}>
<div className="flex max-w-xs flex-col gap-6 p-4">
  <QUI.Field label="Workspace name" hint="Shown on your team's billing page.">
    <QUI.Input placeholder="Acme Inc." />
  </QUI.Field>
  <QUI.Field label="Slug" required error="This slug is already taken.">
    <QUI.Input defaultValue="acme-inc" />
  </QUI.Field>
  <QUI.Field label="Description" size="xl" hint="Optional, up to 200 characters.">
    <QUI.TextArea placeholder="What does your team do?" size="xl" />
  </QUI.Field>
  <QUI.Field>
    <QUI.Checkbox label="Send me product updates" />
  </QUI.Field>
</div>
          </Section>
          <Section title="Menu" align="block" props={{"MenuItem.variant":["neutral","accent","danger"],"MenuItem.selected":"boolean","MenuCheckboxItem.variant":["neutral","accent","danger"],"MenuRadioItem.variant":["neutral","accent","danger"],"MenuRadioItem.marker":["check","radio"]}}>
<div className="flex flex-wrap items-start gap-6 p-4">
  <QUI.Menu>
    <QUI.MenuTrigger render={<QUI.Button label="Open menu" />} />
    <QUI.MenuContent>
      <QUI.MenuItem icon={<QUI.Icon icon={Icons.Pencil} />}>Rename</QUI.MenuItem>
      <QUI.MenuItem icon={<QUI.Icon icon={Icons.Copy} />} trailing={<span className="text-caption-md-regular text-tertiary">⌘D</span>}>
        Duplicate
      </QUI.MenuItem>
      <QUI.MenuSeparator />
      <QUI.MenuGroup>
        <QUI.MenuGroupLabel>Danger zone</QUI.MenuGroupLabel>
        <QUI.MenuItem variant="danger" icon={<QUI.Icon icon={Icons.Trash} />}>
          Delete
        </QUI.MenuItem>
      </QUI.MenuGroup>
    </QUI.MenuContent>
  </QUI.Menu>

  <QUI.Menu>
    <QUI.MenuTrigger render={<QUI.Button variant="secondary" label="View options" />} />
    <QUI.MenuContent>
      <QUI.MenuRadioGroup defaultValue="board">
        <QUI.MenuGroupLabel>Show as</QUI.MenuGroupLabel>
        <QUI.MenuRadioItem value="list">List</QUI.MenuRadioItem>
        <QUI.MenuRadioItem value="board">Board</QUI.MenuRadioItem>
        <QUI.MenuRadioItem value="calendar">Calendar</QUI.MenuRadioItem>
      </QUI.MenuRadioGroup>
      <QUI.MenuSeparator />
      <QUI.MenuCheckboxItem defaultChecked>Show sub-issues</QUI.MenuCheckboxItem>
      <QUI.MenuCheckboxItem>Show completed</QUI.MenuCheckboxItem>
    </QUI.MenuContent>
  </QUI.Menu>
</div>
          </Section>
          <Section title="Pagination" align="block" props={{}}>
<div className="flex flex-col gap-4 p-4">
  <QUI.Pagination page={1} pageCount={5} onPageChange={() => {}} />
  <QUI.Pagination page={6} pageCount={12} onPageChange={() => {}} />
  <QUI.Pagination page={1} pageCount={1} onPageChange={() => {}} />
</div>
          </Section>
          <Section title="Popover" align="row" props={{"variant":["rich","text"],"side":["top","bottom","left","right"],"align":["start","center","end"]}}>
<QUI.Popover>
  <QUI.PopoverTrigger render={<QUI.Button label="Open popover" variant="secondary" />} />
  <QUI.PopoverContent>
    <QUI.PopoverTitle>Notification settings</QUI.PopoverTitle>
    <QUI.PopoverBody>
      <p className="text-body-xs-regular text-secondary">Choose how you want to be notified about activity.</p>
    </QUI.PopoverBody>
  </QUI.PopoverContent>
</QUI.Popover>
          </Section>
          <Section title="Select" align="block" props={{"size":["md","lg","xl","2xl"],"disabled":"boolean","required":"boolean","readOnly":"boolean","multiple":"boolean"}}>
<div className="flex flex-col gap-4 p-4">
  <QUI.Select items={[{ label: "Backlog", value: "backlog" }, { label: "In Progress", value: "in-progress" }, { label: "Done", value: "done" }]} defaultValue="backlog">
    <QUI.SelectTrigger placeholder="Select a status" className="w-56" />
    <QUI.SelectContent>
      <QUI.SelectGroup>
        <QUI.SelectGroupLabel>Status</QUI.SelectGroupLabel>
        <QUI.SelectItem value="backlog">Backlog</QUI.SelectItem>
        <QUI.SelectItem value="in-progress">In Progress</QUI.SelectItem>
        <QUI.SelectSeparator />
        <QUI.SelectItem value="done">Done</QUI.SelectItem>
      </QUI.SelectGroup>
    </QUI.SelectContent>
  </QUI.Select>
  <QUI.Select disabled>
    <QUI.SelectTrigger placeholder="Disabled" className="w-56" />
    <QUI.SelectContent>
      <QUI.SelectItem value="a">Option A</QUI.SelectItem>
    </QUI.SelectContent>
  </QUI.Select>
</div>
          </Section>
          <Section title="Tabs" align="block" props={{"variant":["contained","underline"],"stretch":["auto","full"],"disabled":"boolean"}}>
<div className="flex w-full flex-col gap-8 p-4">
  <QUI.Tabs defaultValue="board">
    <QUI.TabsList>
      <QUI.Tab value="board" label="Board" icon={<QUI.Icon icon={Icons.Grid} />} />
      <QUI.Tab value="list" label="List" icon={<QUI.Icon icon={Icons.List} />} />
      <QUI.Tab value="timeline" label="Timeline" disabled />
    </QUI.TabsList>
    <QUI.TabsPanel value="board">Board view content.</QUI.TabsPanel>
    <QUI.TabsPanel value="list">List view content.</QUI.TabsPanel>
    <QUI.TabsPanel value="timeline">Timeline view content.</QUI.TabsPanel>
  </QUI.Tabs>
  <QUI.Tabs variant="underline" defaultValue="overview">
    <QUI.TabsList>
      <QUI.Tab value="overview" label="Overview" />
      <QUI.Tab value="activity" label="Activity" />
      <QUI.Tab value="settings" label="Settings" />
    </QUI.TabsList>
    <QUI.TabsPanel value="overview">Overview content.</QUI.TabsPanel>
    <QUI.TabsPanel value="activity">Activity content.</QUI.TabsPanel>
    <QUI.TabsPanel value="settings">Settings content.</QUI.TabsPanel>
  </QUI.Tabs>
</div>
          </Section>
          <Section title="Toast" align="block" props={{"timeout":["number"],"limit":["number"]}}>
<QUI.ToastProvider>
  <QUI.ToastLauncher />
</QUI.ToastProvider>
          </Section>
        </div>
      </div>
    </div>
  );
}
